# Generated by Django 2.2.1 on 2019-05-29 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20190528_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='viewed_by',
            field=models.CharField(choices=[('all', 'all'), ('some', 'some')], default='all', max_length=4),
        ),
    ]
